'use client'

import GlobalStyles from "@/design_system/lib/globalStyles"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <GlobalStyles/>
    <html lang="en">
      <body>{children}</body>
    </html>
    </>
  )
}
